Fix/optimize card priority calculation and fix learn span behavior
open-spaced-repetition/fsrs-rs pull request #263
Opened 2024-12-23 07:35 UTC by L-M-Sherlock

This PR includes several improvements to the FSRS simulator:

1. Enhanced card priority calculation:
   - Modified priority tuple to use `i32` instead of `usize`
   - Adjusted difficulty scaling for accuracy in priority calculation
   - Added filtering for cards beyond learn span
2. Added new test case:
   - Validates that changing learn span doesn't affect review counts per day in the same date

2024-12-23 13:44 UTC, Luc-Mcgrady requested changes
The learn_span still effects the earlier cards in my deck.
The test fails if you up the numbers high enough

![image](https://github.com/user-attachments/assets/3caee126-6f92-4e49-a292-b35f3ea694ec)

I'll dm you a deck if the test isn't enough.

2024-12-23 13:44 UTC, Luc-Mcgrady commented on src/optimal_retention.rs
> +
```suggestion
    #[test]
    fn changing_learn_span_should_get_same_review_cnt_per_day() -> Result<()> {
        const LOWER: usize = 365;
        const DECK_SIZE: usize = 1000;

        let cards = vec![Card {
            difficulty: 5.0,
            stability: 5.0,
            last_date: -5.0,
            due: 5.0,
        }];

        let config = SimulatorConfig {
            learn_span: LOWER,
            learn_limit: 10,
            deck_size: DECK_SIZE,
            ..Default::default()
        };
        let (_, review_cnt_per_day_10, _, _) =
            simulate(&config, &DEFAULT_PARAMETERS, 0.9, None, Some(cards.clone()))?;
        let config = SimulatorConfig {
            learn_span: LOWER + 10,
            learn_limit: 10,
            deck_size: DECK_SIZE,
            ..Default::default()
        };
        let (_, review_cnt_per_day_11, _, _) =
            simulate(&config, &DEFAULT_PARAMETERS, 0.9, None, Some(cards))?;

        // Compare first LOWER items of review_cnt_per_day arrays
        for i in 0..LOWER {
            assert_eq!(
                review_cnt_per_day_10[i], review_cnt_per_day_11[i],
                "at index {}",
                i
            );
        }
        Ok(())
    }
```

2024-12-23 15:32 UTC, L-M-Sherlock commented
The inconsistency starts from here:

<img width="1124" alt="image" src="https://github.com/user-attachments/assets/fe53642e-ecbb-439b-8f5a-5766b0303a14" />

2024-12-23 16:25 UTC, L-M-Sherlock commented
@Luc-Mcgrady I hope the latest commit solve your problem.

2024-12-23 16:26 UTC, Luc-Mcgrady commented
![image](https://github.com/user-attachments/assets/cf79fb4c-b50b-40c6-b3ef-0fc77e785ba1)

It's still weird in Anki but I can't get the test to fail. I'm guessing this might be a problem with anki's code?

2024-12-23 16:38 UTC, L-M-Sherlock commented
> It's still weird in Anki but I can't get the test to fail. I'm guessing this might be a problem with anki's code?

Could you use `dbg` to print the input args from your Anki?

2024-12-23 16:48 UTC, Luc-Mcgrady commented
```
[rslib/src/scheduler/fsrs/simulator.rs:32:9] &req = SimulateFsrsReviewRequest {
    params: [
        0.08572003,
        0.40419477,
        4.1386,
        19.5147,
        5.3538256,
        1.4269736,
        0.9058566,
        8.294402e-5,
        1.3015078,
        0.016733568,
        0.6890899,
        2.0352721,
        0.15819947,
        0.2383912,
        1.4175994,
        0.027590245,
        2.8237,
    ],
    desired_retention: 0.8,
    deck_size: 0,
    days_to_simulate: 10,
    new_limit: 0,
    review_limit: 200,
    max_interval: 36500,
    search: "preset:\"Geography\" -is:suspended",
}
[rslib/src/scheduler/fsrs/simulator.rs:32:9] &req = SimulateFsrsReviewRequest {
    params: [
        0.08572003,
        0.40419477,
        4.1386,
        19.5147,
        5.3538256,
        1.4269736,
        0.9058566,
        8.294402e-5,
        1.3015078,
        0.016733568,
        0.6890899,
        2.0352721,
        0.15819947,
        0.2383912,
        1.4175994,
        0.027590245,
        2.8237,
    ],
    desired_retention: 0.8,
    deck_size: 0,
    days_to_simulate: 20,
    new_limit: 0,
    review_limit: 200,
    max_interval: 36500,
    search: "preset:\"Geography\" -is:suspended",
}
```

![image](https://github.com/user-attachments/assets/32edd84a-2c86-43e7-8dd3-30ddabf0c239)

It does set the due date of certain cards to the limit but I cant see how that would effect anything

2024-12-23 16:52 UTC, L-M-Sherlock commented
The due affects the priority. Maybe it causes the inconsistency.

2024-12-23 17:00 UTC, L-M-Sherlock commented
Weird. These cards are new, so they are filtered in the simulator:

https://github.com/open-spaced-repetition/fsrs-rs/blob/0625bfaf0cf46c5d877ace9019b14113c6193263/src/optimal_retention.rs#L189-L194

2024-12-23 17:12 UTC, Luc-Mcgrady commented
![image](https://github.com/user-attachments/assets/5da0037f-77f9-4965-a005-17befa22d05c)

Well I just copied the entire output of my deck into the rs file, and besides making my IDE cry I think it proves its not Anki's problem

2024-12-23 17:56 UTC, Luc-Mcgrady requested changes

2024-12-23 17:56 UTC, Luc-Mcgrady commented on src/optimal_retention.rs
> +        }
```suggestion
```

![image](https://github.com/user-attachments/assets/39115917-66e9-4fdd-86e1-d2a2fe5142b5)

Got it.

2024-12-24 02:13 UTC, L-M-Sherlock commented
Nice! Thanks for your assistance in fixing the bug~

2024-12-24 02:14 UTC, merged